### ISSUE TITLE
Support for Palenight equinusocio/material-theme

### ISSUE THREAD

**Issue by wprater** [Microsoft/vscode-themes#17]
Would love to see a port of Palenight theme
https://github.com/equinusocio/material-theme/blob/develop/Material-Theme-Palenight.sublime-theme

refs https://github.com/equinusocio/material-theme/issues/565

**Comment by XAMelleOH** [comment]
Any updates on this?

**Comment by egamma** [comment]
This is best done as an extension available from the market place. We have currently no plans to expand the set of themes that we bundle with VS Code and I'm closing this issue.

For information on how to import a theme please see https://code.visualstudio.com/docs/customization/themes#_adding-a-new-theme.

**Comment by equinusocio** [comment]
@wprater @XAMelleOH Hi guys, when UI mod will be available i will make the official Material Theme extension. Stay tuned https://github.com/equinusocio/vsc-material-theme
