### ISSUE TITLE
HTML file with Tomorrow Night is all red

### ISSUE THREAD

**Issue by trumbitta** [Microsoft/vscode-themes#18]
![image](https://cloud.githubusercontent.com/assets/462705/21615265/133c7ff8-d1dd-11e6-8e29-17c4c3ce4587.png)

JavaScript and TypeScript seem to work fine.
Only color theme installed is: Tomorrow and Tomorrow Night Theme Kit

VS Code 1.8.1

**Comment by andrewmartin** [comment]
👍  seeing this too!

**Comment by aeschli** [comment]
This looks better in 1.9.
![image](https://cloud.githubusercontent.com/assets/6461412/22349115/989b0104-e40e-11e6-8f43-e469d39ee64b.png)

Tomorrow Night is not part of VSCode. Please file issues directly against the [extension](https://github.com/Microsoft/vscode-themes/issues)

**Comment by trumbitta** [comment]
Good news :) is 1.9 soon to be released?

**Comment by aeschli** [comment]
Yes, in about a week. In the meantime you can already try the [insiders build](https://code.visualstudio.com/insiders).
