### ISSUE TITLE
predawn: python type hinting breaks highlighting

### ISSUE THREAD

**Issue by KorayUlusan** [microsoft/vscode-themes#39]
```python
def dot_on_n_dimensional_cube(n: int) -> list:
    '''docstring here''' 
    pass
```
breaks the docstring highlighting and highlighting below in predawn theme

**Comment by connor4312** [comment]
\extPython

**Comment by KorayUlusan** [comment]
This issue is caused by `Python for VSCode` by `Thomas Haakon Townsend` extension. 

This theme works as expected.
