### ISSUE TITLE
Incorrect Syntax Highlighting for CSS Properties and Values API

### ISSUE THREAD

**Issue by rlgreen91** [microsoft/vscode-themes#40]
When using the CSS Properties and Values API in a CSS file, I'm running into issues with incorrect syntax highlighting that seems to stem from an unknown rule warning for `@property`.  Below is a screenshot of my CSS file, with the warning displayed:

![image](https://user-images.githubusercontent.com/1738068/147860742-aa52cc23-c6f5-4aed-885c-4585d5b5173e.png)

My current version of Visual Studio Code is 1.62.3, my OS is Windows 11, and the theme is Monokai Dimmed.  However, I did try switching between a number of the built-in themes and experienced the same results.

Here is a link to the corresponding rule definition in MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/@property

**Comment by alexr00** [comment]
@rlgreen91 can you share a copy/pastable snippet that I can reproduce the issue with?

**Comment by rlgreen91** [comment]
Sure thing:

```
@property --pattern-seed {
  syntax: "<number>";
  initial-value: 1000;
  inherits: true;
}

@property --pattern-colors {
  syntax: "<color>#";
  initial-value: #161511, #dd6d45, #f2f2f2;
}

@property --pattern-speck-count {
  syntax: "<number>";
  initial-value: 3000;
  inherits: true;
}

@property --pattern-speck-min-size {
  syntx: "<number>";
  initial-value: 0;
  inherits: true;
}

@property --pattern-spec-max-size {
  syntax: "<number>";
  initial-value: 3;
  inherits: true;
}

body {
  margin: 0;
}

.worklet-canvas {
  width: 100vw;
  height: 100vw;
  background-color: #90c3a5;
  background-image: paint(tinySpecksPattern);
}
```

**Comment by alexr00** [comment]
Thanks @rlgreen91! The incorrect syntax highlighting is coming from the grammar we use for syntax highlighting. Upstream issue: https://github.com/atom/language-css/issues/187

The squiggles under `@property` are coming from the built in css extension, and indicate an issue with your css.
