### ISSUE TITLE
Respect terms of original licenses

### ISSUE THREAD

**Issue by idleberg** [Microsoft/vscode-themes#9]
I noticed that Microsoft licensed all of the included themes under The MIT License. I'm not sure if this is always appropriate, since none of the themes are the work of Microsoft.
- _Predawn_, _Material_ and _Tomorrow_ are released under The MIT License, so it's my understanding the original authors –[Jamie Wilson](https://github.com/jamiewilson/predawn/blob/master/LICENSE.txt), [Mattias Astorino](https://github.com/equinusocio/material-theme/blob/develop/LICENSE.md) and [Chris Kempson](https://github.com/chriskempson/base16/blob/master/LICENSE.md)– should remain in the license.
- _3024_ is my own theme and was released under the [Public Domain Mark](https://github.com/0x3024/TextMate/blob/master/3024%20Day.tmTheme#L7). I'm not sure if that allows re-releasing it under a different license. It's my work and I don't care that much, but it's about the details.
- _1337_ does not specify any license, which to my understanding means “All Rights Reserved”. I don't think it can be released under a licensed the author hasn't approved of.

I understand that this confusion is likely caused by taking the themes from the [Colorsublime](https://github.com/Colorsublime/Colorsublime-Themes) repository, so it's probably their fault. Yet, that doesn't make it right.

**Comment by chrisdias** [comment]
@tyriar i thought you had fixed these??

**Comment by Tyriar** [comment]
I created https://github.com/MarkMichos/1337-Scheme/issues/7 for 1337. Material and predawn are already included in https://github.com/Microsoft/vscode-themes/blob/master/thirdpartynotices.txt, we should include the [tomorrow license](https://github.com/chriskempson/tomorrow-theme/blob/master/LICENSE.md) and while I don't think we need to, including 3024 as well in thirdpartynotices.txt wouldn't hurt.

**Comment by chrisdias** [comment]
Ok, thanks.  the problem with the tomorrow license is that it refers to Base16 and not the tomorrow-theme!  I submitted an issue there to fix https://github.com/chriskempson/tomorrow-theme/issues/326.

**Comment by chrisdias** [comment]
I will open a new issue for 1337.

**Comment by Tyriar** [comment]
Thanks @chrisdias!

**Comment by MarkMichos** [comment]
Hi guys!

What is this topic about? I don't quite get it.

**Comment by chrisdias** [comment]
@MarkMichos would it be possible to include a license in your [1337 theme repo](https://github.com/MarkMichos/1337-Scheme)? This makes it much easier for us to redistribute your theme as we know what the right license terms are and we know how to properly attribute the license.   

@Tyriar submitted https://github.com/MarkMichos/1337-Scheme/issues/7 for this. If it is at all possible, the MIT license is the easiest for us to consume.

**Comment by MarkMichos** [comment]
@chrisdias License should now be included

**Comment by Tyriar** [comment]
@MarkMichos included your license and added a link to the readme (which will show up after publish).

@chrisdias can you publish to the marketplace?

**Comment by chrisdias** [comment]
published!
